export const countries = [
  { name: 'Botswana', code: 'BW', currency_code: 'BWP', currency_symbol: 'P' },
  { name: 'China', code: 'CN', currency_code: 'CNY', currency_symbol: '¥' },
  { name: 'Ethiopia', code: 'ET', currency_code: 'ETB', currency_symbol: 'Br' },
  { name: 'Eswatini', code: 'SZ', currency_code: 'SZL', currency_symbol: 'L' },
  { name: 'Ghana', code: 'GH', currency_code: 'GHS', currency_symbol: '₵' },
  { name: 'Kenya', code: 'KE', currency_code: 'KES', currency_symbol: 'KSh' },
  { name: 'Lesotho', code: 'LS', currency_code: 'LSL', currency_symbol: 'M' },
  { name: 'Malawi', code: 'MW', currency_code: 'MWK', currency_symbol: 'MK' },
  { name: 'Mozambique', code: 'MZ', currency_code: 'MZN', currency_symbol: 'MT' },
  { name: 'Namibia', code: 'NA', currency_code: 'NAD', currency_symbol: 'N$' },
  { name: 'Nigeria', code: 'NG', currency_code: 'NGN', currency_symbol: '₦' },
  { name: 'Rwanda', code: 'RW', currency_code: 'RWF', currency_symbol: 'Fr' },
  { name: 'South Africa', code: 'ZA', currency_code: 'ZAR', currency_symbol: 'R' },
  { name: 'Tanzania', code: 'TZ', currency_code: 'TZS', currency_symbol: 'TSh' },
  { name: 'Uganda', code: 'UG', currency_code: 'UGX', currency_symbol: 'USh' },
  { name: 'Zambia', code: 'ZM', currency_code: 'ZMW', currency_symbol: 'ZK' },
  { name: 'Zimbabwe', code: 'ZW', currency_code: 'USD', currency_symbol: '$' },
  { name: 'Other', code: 'OT', currency_code: 'USD', currency_symbol: '$' },
]